### ISSUE TITLE
Person Account issue

### ISSUE THREAD

**Issue by travadactyl** [codeulike/SandboxBerry#12]
When attempting to insert Person Account records, I'm getting an error:

Error when inserting Account <accountId> into target: Error Unable to create/update fields: Name. Please check the security settings of this field and verify that it is read/write for your profile or permission set. Status Code INVALID_FIELD_FOR_INSERT_UPDATE Fields Name

When creating a Person Account via the UI, LastName is required while "Name" isn't used.  Is there a way to do something like:
		<SbbFieldOption ApiName="Name" ReplaceApiName= "LastName" />  ?? I tried that and it didn't work, so wondering if there's something similar that would work, or a way to recognize PersonAccount as its own object?

**Comment by codeulike** [comment]
Hmm interesting.

I have used Sandboxberry on instances that have Person Accounts - if you transfer the Contact records the Account records should sort themselves out. Is that what you are doing? (i.e. do you have SbbObject entries in the config for just Contact or are you doing Contact and Account)

**Comment by travadactyl** [comment]
I actually ended up getting it figured out.  I did two separate filters:

```
<SbbObject ApiName="Account" Filter="TestData__c = true and recordtype.developername  = 'personAccount'">
	<SbbFieldOptions>
		<SbbFieldOption ApiName="Name" Skip ="true" />
```

Along with:
`<SbbObject ApiName="Account" Filter="TestData__c = true and recordtype.developername  = 'industrieshousehold'">
`
leaving off the "skip Name".  It ended up working well enough to get the sandbox loaded with some data.  

I just wanted to say thanks so much for the time you spent creating this.  I know it's an older program that may no longer work someday, but there's so little effort on my part for such a huge benefit.  Not all heroes wear capes!  Unless you do, in which case, carry on!

**Comment by marmanyous0** [comment]
Hi
when trying to login into the instance it fails and shows an error message "Unexpected error: Error while logging in to Source: LOGIN_MUST_USE_SECURITY_TOKEN" as per the attached screenshot.
Where should I enter my security token?

![image](https://user-images.githubusercontent.com/88323373/155327654-f31fa174-f666-44ec-bfaf-4176444a8e8f.png)

**Comment by codeulike** [comment]
You append it on the end of the password
