### ISSUE TITLE
Out of memory error occurs

### ISSUE THREAD

**Issue by Tosakai2** [codeulike/SandboxBerry#3]
Hi,

When I operate Opportunity object below error occurs.

Unexpected error: Error while fetching data for Opportunity: 種類 'System.OutOfMemoryException' の例外がスローされました。 

Is there any alternative way how to avoid this error?

**Comment by mwanchap** [comment]
@Tosakai2 how many records are you loading? Not just opportunity records, but like total records for all objects.  I was thinking that since SandboxBerry stores all its data in memory, it might have these problems while transferring very large numbers of records...

**Comment by codeulike** [comment]
No one else ever had this
