### ISSUE TITLE
Update is not happening

### ISSUE THREAD

**Issue by sjambunathan** [codeulike/SandboxBerry#7]
Every time when I transfer the records from prod to sandbox, It is not getting updated instead It creates a new record every time. Can you help me fix this?

**Comment by codeulike** [comment]
It can't do updates - a side effect of the way it juggles ids when transferring data.
There is a delete function somewhere in the menu which you can use to clear out what was transferred last time - be careful though.

**Comment by codeulike** [comment]
By design
